### ISSUE TITLE
Using HPC / cluster to use mzmine?

### ISSUE THREAD

**Issue by marwa38** [mzmine/mzmine#2023]
Hi team 
I wonder if you have any advice to the IT team as I will ask them to allow me to use mzmine on the HPC of the university. It is slurm-based [here](https://www.abdn.ac.uk/research/digital-research/hpc-for-research-1097.php).
I will just share your github and ask them to allow me to run your mzmine as they are the one who install, etc.
Thanks 
Marwa

**Comment by SteffenHeu** [comment]
Hi marwa,

we cannot help you with the specifics of your server, but there are some points to consider:

- You can set/limit used memory here: https://mzmine.github.io/mzmine_documentation/performance.html#maximum-memory
- The threads parameter in mzmine only limits the concurrent tasks, not hte number of cpu cores used. you can use this parameter: `-XX:ActiveProcessorCount=<count>` to limit the cpu usage on a server. Add it where the previous option sets the memory
- General CLI usage follow this guide: https://mzmine.github.io/mzmine_documentation/commandline_tool.html (a valid user must be available)
- CLI arguments are listed here: https://mzmine.github.io/mzmine_documentation/commandline_tool.html#argument-table

**Comment by ansgarkorf** [comment]
Hi Marwa,
did it work? Can we close this?

**Comment by marwa38** [comment]
i will let you know before the start of next week hopefully, I requested a access to cluster and I am figuring it out.

**Comment by Sanchezillana** [comment]
I’m also exploring this. I aim to process over 500 DDA samples, including a library search, using mzmine. Currently, I’m working on a local setup with my PC (i7-13700, 64GB RAM) via the command line, utilizing a .mzbatch file generated through the wizard (which I assume is equivalent to .xml).

I’m curious whether transitioning to the HPC environment will significantly boost performance, considering the differences in hardware. My PC has 24 cores at 4GHz with 64GB RAM, whereas a HPC node I’ll be using has 32 cores at 3GHz and 192GB RAM. However, since the single-core speed of the HPC is slower, I'm wondering if the performance gains will offset that.

From what I understand, in this version of mzmine we’re limited to using a single node on the cluster and cannot set up MPI jobs across multiple nodes. Additionally, I anticipate some challenges in getting everything to run smoothly on the CentOS-based HPC setup. I’ll keep you updated on how it goes.

**Comment by Sanchezillana** [comment]
I was also wondering if we can have feedback during the running of the CLI mode. I mean, a kind of .log file wich is dynamically edited with the modules running and we can read.

**Comment by Sanchezillana** [comment]
So far, I’ve successfully launched jobs via SLURM on the login node, which is interactive and has X11 enabled. This was just for testing purposes, as the login node is quite limited and it doesn't make sense to use HPC resources this way. However, when I attempt to run jobs on the compute nodes, I encounter the following error:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /storage/scratch/lv82/lv82834/mzmine_4_2_0/lib/runtime/lib/libawt_xawt.so: libXtst.so.6: cannot open shared object file: No such file or directory
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2399)
	at java.base/java.lang.Runtime.load0(Runtime.java:852)
	at java.base/java.lang.System.load(System.java:2030)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:259)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:249)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2408)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:916)
	at java.base/java.lang.System.loadLibrary(System.java:2068)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1384)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1382)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1381)
	at java.desktop/java.awt.Toolkit.initStatic(Toolkit.java:1419)
	at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1393)
	at java.desktop/java.awt.Font.<clinit>(Font.java:288)
	at org.jfree.chart.axis.Axis.<clinit>(Axis.java:97)
	at org.jfree.chart.StandardChartTheme.<init>(StandardChartTheme.java:211)
	at org.jfree.chart.StandardChartTheme.<init>(StandardChartTheme.java:293)
	at io.github.mzmine.gui.chartbasics.chartthemes.EStandardChartTheme.<init>(EStandardChartTheme.java:108)
	at io.github.mzmine.main.impl.MZmineConfigurationImpl.<init>(MZmineConfigurationImpl.java:97)
	at io.github.mzmine.main.ConfigService.<clinit>(ConfigService.java:41)
	at io.github.mzmine.main.MZmineCore.main(MZmineCore.java:155)
```

It seems to be related to missing X11 libraries (specifically libXtst.so.6). I’m planning to request the installation of these libraries on the compute nodes, but I’m uncertain if this will fully resolve the issue or if there are better alternatives.

Has anyone faced similar issues or have advice on running mzmine in an HPC environment without X11 dependencies?  Any insights would be greatly appreciated!

**Comment by Sanchezillana** [comment]
> I’m also exploring this. I aim to process over 500 DDA samples, including a library search, using mzmine. Currently, I’m working on a local setup with my PC (i7-13700, 64GB RAM) via the command line, utilizing a .mzbatch file generated through the wizard (which I assume is equivalent to .xml).
> 
> I’m curious whether transitioning to the HPC environment will significantly boost performance, considering the differences in hardware. My PC has 24 cores at 4GHz with 64GB RAM, whereas a HPC node I’ll be using has 32 cores at 3GHz and 192GB RAM. However, since the single-core speed of the HPC is slower, I'm wondering if the performance gains will offset that.
> 
> From what I understand, in this version of mzmine we’re limited to using a single node on the cluster and cannot set up MPI jobs across multiple nodes. Additionally, I anticipate some challenges in getting everything to run smoothly on the CentOS-based HPC setup. I’ll keep you updated on how it goes.

I should also mention that my local PC crashes during batch processing of 500 samples, specifically at the 'Local Min Feature Resolver' step (around 50% progress). The error I receive is:

`memory issues java.lang.OutOfMemoryError: Java heap space`

I’ve tried several approaches to resolve this, including increasing virtual memory, reducing the number of processing threads, and using Process Lasso to assign affinity to P-cores. Unfortunately, none of these solutions have worked so far (see the attached batch file, the same I testing in the cluster).
[batch.zip](https://github.com/user-attachments/files/16901336/batch.zip)

**Comment by Sanchezillana** [comment]
After requesting the installation of the necessary libXtst.so.6 library, I was able to run the program successfully on a high-memory node (1.5 TB of RAM). During batch processing (without library search), mzmine consumed around 300 GB of memory, which seems quite excessive to me for this type of task.

The HPC support team suggested that this might be indicative of a memory leak within the program. Given this significant memory usage, I'm wondering if anyone else has encountered similar issues or has suggestions for optimizing memory consumption in mzmine.

For now, I’ll continue using the HPC cluster, but any insights or advice on how to handle this memory usage would be greatly appreciated."

**Comment by ansgarkorf** [comment]
Hi,
thanks for providing all the important information. It indeed sounds like a memory leak. Are you able to track when the RAM usage goes up? Maybe you can determine which module is responsible for the heavy usage.

Can you also check in the settings under general "Keep in memory"? It is possible to set it to ALL. Make sure to set it to NONE.
<img width="639" alt="image" src="https://github.com/user-attachments/assets/5c6001f6-fb95-48fa-9a4f-8321eef44b95">

**Comment by Sanchezillana** [comment]
> Hi, thanks for providing all the important information. It indeed sounds like a memory leak. Are you able to track when the RAM usage goes up? Maybe you can determine which module is responsible for the heavy usage.
> 
> Can you also check in the settings under general "Keep in memory"? It is possible to set it to ALL. Make sure to set it to NONE. <img alt="image" width="639" src="https://private-user-images.githubusercontent.com/27132602/365203648-5c6001f6-fb95-48fa-9a4f-8321eef44b95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MzM5NTYsIm5iZiI6MTcyNTYzMzY1NiwicGF0aCI6Ii8yNzEzMjYwMi8zNjUyMDM2NDgtNWM2MDAxZjYtZmI5NS00OGZhLTlhNGYtODMyMWVlZjQ0Yjk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDE0NDA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0MzEzMmFkOWQ3YmRkMWZlNWFhNjExOWJmNjlhMTAyODVmMzI5YjBlM2UxODM1NTNhMzRkYzdmYjM4Mzc3NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B4mEb6t4wbsMtkNJgsSo4_q4eH7MogrDMT9f5v-_hoA">

Yeah, sure it is in none. When I run the in CLI mode I think that is defult also in none. The memory crazyness is always during 'Local Min Feature Resolver'. But it increases progresively during the run.

**Comment by Sanchezillana** [comment]
Ok, I finally managed to process all 500 DDA samples on a high-memory node (72 cores @ 3GHz, 1.5 TB of RAM). At its peak, MZmine utilized around 1.1 TB of RAM, which is a substantial portion of the node’s capacity. The entire job took approximately 6 hours to complete. Given the complexity and scale of the job, I’m starting to consider that such high memory usage might be expected... However, I'm still curious if there are any known optimizations or configurations that could help reduce memory consumption or improve overall performance. I’m now planning to optimize the processing workflow, starting from this recent successful run. My next steps include conducting library searches and further fine-tuning the processing parameters. I'll keep the community updated on any progress or findings. 

`2024-09-08 23:17:58 INFO   io.github.mzmine.modules.batchmode.BatchTask run Finished a batch of 17 steps
2024-09-08 23:17:58 INFO   io.github.mzmine.modules.batchmode.BatchTask printBatchTimes Timing: Whole batch took PT5H59M19.589183695S to finish
Step 1: Import MS data took PT57.815294795S to finish
Step 2: Chromatogram builder took PT1M36.598184368S to finish
Step 3: Smoothing took PT1M10.540471673S to finish
Step 4: Local minimum feature resolver took PT2M40.424936179S to finish
Step 5: 13C isotope filter (formerly: isotope grouper) took PT40.448704232S to finish
Step 6: Isotopic peaks finder took PT9.847988839S to finish
Step 7: Join aligner took PT4M46.719240044S to finish
Step 8: Feature list rows filter took PT16M58.263264139S to finish
Step 9: Peak finder (multithreaded) took PT29M7.158535494S to finish
Step 10: Duplicate peak filter took PT2H38M2.077070383S to finish
Step 11: Correlation grouping (metaCorrelate) took PT2H9M41.953462506S to finish
Step 12: Ion identity networking took PT2.125329372S to finish
Step 13: Spectral / Molecular Networking took PT1M27.219474913S to finish
Step 14: Export spectral networks to graphml (FBMN/IIMN) took PT3M2.036248481S to finish
Step 15: Export molecular networking files (e.g., GNPS, FBMN, IIMN, MetGem) took PT4M26.674665816S to finish
Step 16: Export for SIRIUS took PT4M29.417553734S to finish
Step 17: Export all annotations to CSV file took PT0.264971242S to finish
`

**Comment by ansgarkorf** [comment]
Thanks for all the details. We found something. Can you please try processing again with the latest development release? version 4.2.8

**Comment by Sanchezillana** [comment]
> Thanks for all the details. We found something. Can you please try processing again with the latest development release? version 4.2.8

Thank you! I know how to compile fow windows in my Desktop but not how to create the portable for linux for the HPC. I will try in my desktop first. 

Ángel SI

**Comment by Sanchezillana** [comment]
> > Thanks for all the details. We found something. Can you please try processing again with the latest development release? version 4.2.8
> 
> Thank you! I know how to compile fow windows in my Desktop but not how to create the portable for linux for the HPC. I will try in my desktop first.
> 
> Ángel SI

Hi @ansgarkorf. I built mzmine 4.2.8 with Gradle in IntelliJ in my Windows PC and ran the batch and I have also the memory issue when processing the 500 DDA samples.

**Comment by Sanchezillana** [comment]
Hi @ansgarkorf. I built mzmine 4.2.8 with Gradle in IntelliJ in my Windows PC and ran the batch and I have also the memory issue when processing the 500 DDA samples.

**Comment by Sanchezillana** [comment]
Some feedback @ansgarkorf: 

The admins have installed the jdk21 in the HPC and I ran ./gradlew to build the sources. I got: 

```
> Task :help
Welcome to Gradle 8.10.
To run a build, run gradlew <task> ...
To see a list of available tasks, run gradlew tasks
To see more detail about a task, run gradlew help --task <task>
To see a list of command-line options, run gradlew --help
For more detail on using Gradle, see https://docs.gradle.org/8.10/userguide/command_line_interface.html
For troubleshooting, visit https://help.gradle.org/

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.10/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD SUCCESSFUL in 1m 30s
11 actionable tasks: 11 executed
```
But there is not build/jpackage folder. Anyway, the users cannot write in /. Do you know where the package is saved? Can I change this directory?

**Comment by ansgarkorf** [comment]
Hi,
we will provide ready to use builds also for the recent development builds and we are still looking into the potential memory leak.

**Comment by Sanchezillana** [comment]
Thank you so much!

**Comment by robinschmid** [comment]
Thanks for the detailed report.

Performance tuning options are described here:
https://mzmine.github.io/mzmine_documentation/performance.html

Can you share a representative sample of your 500 batch and the latest batch file? 

1. For a large study I always suggest to be a bit more strict with the filtering early on. Increase the noise levels and minimum height and that a feature needs to be detected in 10 - 20% of your samples. For clinical maybe even more than that depending if unique features in individual samples are of interest or if it is more about solid statistics. 
2. If the data was acquired in multiple batches - import a few samples from each batch and see if there are any retention time shifts. This will make the alignment harder and the number of features will explode. 
3. Even with higher noise thresholds, gap filling will detect lower intensity features if a feature was high enough in those X% of samples.

Profiling a Java application can be hard. You can check out VisualVM or the Profilers in IntelliJ and compare memory dumps / live monitors.
If you provide 1TB of RAM mzmine will most likely just slowly fill it all up and and only perform garbage collection if really needed. This is the highest throughput method, and should get you the results fastest. We could check and maybe add an option to run GC after key steps to keep the maximum memory consumption more in check.

In the GUI you can click on the bottom right RAM monitor and it will perform garbage collection. Or in VisualVM you can also trigger GC and see that mzmine does not use all of the memory you think it is. The JVM just holds on to the memory and manages it. 

I am interested if you know any other option?

**Comment by robinschmid** [comment]
Also on the server, did you check that the temp directory is accessible and that mzmine is writing temp files there?

**Comment by ansgarkorf** [comment]
Development builds are now available for download.
https://github.com/mzmine/mzmine/releases

**Comment by Sanchezillana** [comment]
Thank you @robinschmid for your feedback. 

> Can you share a representative sample of your 500 batch and the latest batch file?
I have sent you a pooled QC sample via email. We are currently working on this project, and it is quite confidential at the moment.

>  1. For a large study I always suggest to be a bit more strict with the filtering early on. Increase the noise levels and minimum height and that a feature needs to be detected in 10 - 20% of your samples. For clinical maybe even more than that depending if unique features in individual samples are of interest or if it is more about solid statistics.

I am currently using a low signal factor for mass detection in the advanced import. However, I agree that using a factor of 5 for MS1 might be too low. I will optimize this and evaluate the results. It might even work on my desktop PC (64 GB RAM, as mentioned earlier). Right now, it crashes during the chromatogram deconvolution step with a `memory issues java.lang.OutOfMemoryError: Java heap space error`.

>2. If the data was acquired in multiple batches - import a few samples from each batch and see if there are any retention time shifts. This will make the alignment harder and the number of features will explode.
  
The data was acquired in a single batch of 500 samples. While it is a large batch, we haven’t noticed significant batch effects so far, although we plan to assess this as part of the project.

> 3. Even with higher noise thresholds, gap filling will detect lower intensity features if a feature was high enough in those X% of samples.

Understood. I will experiment with higher noise thresholds in both mass and feature detection.

> Profiling a Java application can be hard. You can check out VisualVM or the Profilers in IntelliJ and compare memory dumps / live monitors. If you provide 1TB of RAM mzmine will most likely just slowly fill it all up and and only perform garbage collection if really needed. This is the highest throughput method, and should get you the results fastest. We could check and maybe add an option to run GC after key steps to keep the maximum memory consumption more in check. In the GUI you can click on the bottom right RAM monitor and it will perform garbage collection. Or in VisualVM you can also trigger GC and see that mzmine does not use all of the memory you think it is. The JVM just holds on to the memory and manages it.

I see. GC might indeed be a key factor here. Having an option to trigger GC from the command line would be useful, as currently, it can only be done manually via the GUI, right?

> Also on the server, did you check that the temp directory is accessible and that mzmine is writing temp files there?
With so much memory it could also be faster to just use the RAM and avoid memory mapping but up to your preference.

Yes, each node has a local HDD configured as temp storage (which is deleted after the job finishes), and I’ve set this directory using the ` --temp` option. I initially enabled memory mapping because I suspected memory limitations (the full batch crashed on a node with a 300 GB memory limit).

**Comment by robinschmid** [comment]
you can hookup tools like visualvm and others to a running java application and trigger GC. 
I think a better option would be to add GC after critical steps that produce a lot of garbage. 

Usually I would also leave memory mapping enabled. Just an option to try if memory is no issue at all.

**Comment by robinschmid** [comment]
I looked at your batch and your chromatogram builder and local minimum resolver settings are quite open for noise. 
Which is ok... but this may explain the high RAM requirements. 

In both you could increase the number of scans / data points from 4 to 6 or 7, considering that your chromatographic peak shapes are quite nice. 

You may also want to increase the minimum height to 1E5 or at least a little bit to reduce the number of noisy features. 

![image](https://github.com/user-attachments/assets/ee9a385f-8a84-45ab-842a-3dfdb22c91a7)

In local min resolver increase the chromatographic threshold to 85%, number of data points to 6, height to 1E5, and maybe minimum search range to 0.04 as your peaks are quite narrow. 
![image](https://github.com/user-attachments/assets/0543ba9c-fd97-42a9-925f-12559ae7233c)

Feature list rows filter increase number of samples by percentage - this will scale with the size of your sample set. You can also set it to process in place which is again a little bit faster.
![image](https://github.com/user-attachments/assets/e7c9d0f9-8d54-4c51-a007-bd44063323d7)

**Comment by robinschmid** [comment]
Even with the increased parameters I get 15,000 features in a single sample. So this dataset will be quite complex to process and align. 
Good thing is that you can increase the minimum height and other constraints and then a feature needs to be only detected in X% of the samples to be still considered. The gap filling will then fill the holes produced by high noise thresholds.

**Comment by robinschmid** [comment]
You can find the updated batch here but better you check it out yourself in mzmine, trying to find a good balance.
[biomoval_1_vives.zip](https://github.com/user-attachments/files/16962865/biomoval_1_vives.zip)

**Comment by robinschmid** [comment]
In your datafile, this is the scan with the highest noise amplitude and factor 5 already removes most of the noise... but your minimum feature height was at 5E4 while this is directly in the noise region:
![image](https://github.com/user-attachments/assets/04f007dd-b700-4d28-9631-60370ddef665)

**Comment by Sanchezillana** [comment]
Thank you so much @robinschmid! I'll try the entire batch in the three systems (my desktop, HPC 300 GB RAM, and HPC 1,5 TB RAM).

**Comment by robinschmid** [comment]
I removed some steps so better update your own batch or at least add the remaining steps again. 
I hope this improves the performance and otherwise you can increase some of the thresholds a bit more.

**Comment by robinschmid** [comment]
@Sanchezillana we updated a few things and tweaked the memory options. Memory management was set to best performance and now we are using more of a middle ground. So the GC should also reduce the used memory during the processing if enough space is free after GC. 

We also added -login-console for a pure console login.

Check out the latest test build:
https://github.com/mzmine/mzmine/releases/tag/Development-release

Also we fixed the build for linux. Previously the installer used the wrong package name. Now it should be mzmine. We updated the readme and documentation. It would be a great help if you can check it out and help optimize it if you have any insights:
https://github.com/mzmine/mzmine?tab=readme-ov-file#installation-on-linux

https://mzmine.github.io/mzmine_documentation/getting_started.html#installation-on-linux

https://mzmine.github.io/mzmine_documentation/commandline_tool.html#linux

**Comment by Sanchezillana** [comment]
> @Sanchezillana we updated a few things and tweaked the memory options. Memory management was set to best performance and now we are using more of a middle ground. So the GC should also reduce the used memory during the processing if enough space is free after GC.
> 
> We also added -login-console for a pure console login.
> 
> Check out the latest test build: https://github.com/mzmine/mzmine/releases/tag/Development-release
> 
> Also we fixed the build for linux. Previously the installer used the wrong package name. Now it should be mzmine. We updated the readme and documentation. It would be a great help if you can check it out and help optimize it if you have any insights: https://github.com/mzmine/mzmine?tab=readme-ov-file#installation-on-linux
> 
> https://mzmine.github.io/mzmine_documentation/getting_started.html#installation-on-linux
> 
> https://mzmine.github.io/mzmine_documentation/commandline_tool.html#linux

Thank you so much, @robinschmid and mzio team! This is fantastic news. I will test out the latest build and the updated documentation over the next week and provide feedback. Your efforts are greatly appreciated!

**Comment by robinschmid** [comment]
Would be great to know how the new version compares against the old version

**Comment by Sanchezillana** [comment]
> Would be great to know how the new version compares against the old version. I guess you ran the old version with the adjusted batch file?

Not yet. Now I am preparing classes and refreshing the Nerst Equation and advanced electrochemistry lol. For the next week I can run the updated batch it in both and compare the performance in my PC (if it won't crash) and in the HPC.

**Comment by Sanchezillana** [comment]
Hi @robinschmid !

I've tested the batch with all the files using the latest development build (4.3.10), and I'm still encountering the same memory issue on my desktop PC—it crashes due to memory limitations.

Regarding the HPC, I'm unable to compile the software as per the documentation. I think the issue is that, due to admin policies, users cannot write to the root directory (/). We are only permitted to write in specific folders within /home and /storage/scratch. Is there a way to change the directory for the build/jpackage to a location within these writable areas? Anyway, if I understood correctly, using precompiled Java software on the HPC should not significantly impact performance since Java's runtime optimizations handle most of it. That said, for scientific computing, compiling natively for the HPC’s CPU architecture can improve performance, particularly by leveraging parallelization and vectorization, though this is more relevant for languages like C or Fortran.

For the precompiled versions, we're also encountering the libXtst.so.6 library issue. I resolved this by manually copying the attached file ([library_hpc_issue.zip](https://github.com/user-attachments/files/17187880/library_hpc_issue.zip)) into /lib/runtime/lib. After doing this, the batch file executed successfully. However, the memory usage remains as high as before, necessitating the use of a high-memory node (1.5 TB of RAM) to process my 500 samples.

**Comment by Sanchezillana** [comment]
Hi @robinschmid and team again!

I ran the batch you optimize including additional steps  
![batch](https://github.com/user-attachments/assets/a41aeddd-2e01-4de3-b7d7-302732138745)
 on the HPC I mentioned earlier (72 cores @ 3GHz, 1.5 TB RAM) and included some commands in the scheduler script to monitor memory consumption using jstat every 10 seconds. Specifically, I tracked the following metrics:

S0, S1, E: These represent the "young generation" memory pools, where new objects are created and promoted if they survive garbage collection.
O: The old generation, which stores long-lived objects.
M (Metaspace): Holds class-related metadata.
Garbage Collection Metrics (YGC, YGCT, FGC, FGCT, GCT): Track the activity and time spent in garbage collection.
Additionally, I used ps to extract %MEM and VSZ of the MZmine process.

I’ve attached the MZmine log and the memory log corresponding to this batch. Could you please take a look and share your thoughts on this? 
[output_log.txt](https://github.com/user-attachments/files/17213320/output_log.txt)
[memory_study.txt](https://github.com/user-attachments/files/17213322/memory_study.txt)

**Comment by Sanchezillana** [comment]
Please see the updated files. I have relaunched the job with some minor adjustments to the SLURM script to provide clearer headers in the memory log. Let me know what you think!

[ram_usage_2760628.log](https://github.com/user-attachments/files/17228121/ram_usage_2760628.log)
[omp_2760628.log](https://github.com/user-attachments/files/17228122/omp_2760628.log)

**Comment by Sanchezillana** [comment]
Hi! I've been successfully running several mzmine jobs on our HPC cluster with this configuration until now. I’m trying to save the generated project on the HPC so I can later open it locally to inspect feature profiles, etc. However, when I added the "Save Project" step to the batch, I encountered the following error:

2024-11-11 17:19:21 SEVERE io.github.mzmine.modules.io.projectsave.ProjectSavingTask run Could not delete old file /storage/scratch/lv82/lv82834/mzmine_results/3050806
java.io.IOException: Could not delete old file /storage/scratch/lv82/lv82834/mzmine_results/3050806 

It appears that mzmine cannot delete this "old file" (no idea what file is), and as a result, the project is not saved. Any insights on how to resolve this issue or possible workarounds would be greatly appreciated!
