### ISSUE TITLE
Statistical dashboard doesn't work well with metadata import

### ISSUE THREAD

**Issue by GenesiskaGenesiska** [mzmine/mzmine#2220]
### Basic information

* My operating system and version: MacOS Sequoia, version 15.1
* My mzmine version: 4.3.0

### What happened
It is very nice that now MZMINE has the statistical dashboard to provide PCA, volcano plot, and box plot. I could have them when I excluded the metadata when I imported the data in mswizard; meanwhile, it doesn't work when I include the metadata files. It would be nice to have better visualisation when I could recognise the sample group in the PCA (to see better grouping with colour and clustering) and could categorise the group B with chosen parameters and any better data visualisation with box plot when the metadata could work well. 

Please find the error notification as screenshot, what does it mean with sample type is null?

<img width="1147" alt="Screenshot 2024-11-13 at 2 17 07 PM" src="https://github.com/user-attachments/assets/60691a4f-1f61-45b5-a46a-02569b96115a">

Please find my mzmine project file (batch, savepreset, raw file, and log file) as well here [[]](https://drive.google.com/drive/folders/1Lb6KBXY4ht0BNcCoFuVU62KSLJDkQQr0?usp=share_link)(url)

Many thanks

**Comment by robinschmid** [comment]
This was an issue with the metadata import overwriting the mzmine internal sample type definitions. It should be resolved in the latest development release and in the upcoming release. 
Can you download the latest dev release and try this version?

https://github.com/mzmine/mzmine/releases/tag/Development-release

**Comment by GenesiskaGenesiska** [comment]
Hi Robin, I have downloaded that latest dev release and tried the version. And double checked whether my metadata and samples didn't match as suggested in the notification, as well as for the order of filename in the first column. Meanwhile, this error happened many times; I have tried again and still the same. Any suggestions?

<img width="1147" alt="Screenshot 2024-11-14 at 9 30 51 AM" src="https://github.com/user-attachments/assets/eb771c72-242c-4b79-8b36-d7f5f4808292">

**Comment by GenesiskaGenesiska** [comment]
Hi Robin,

By the latest version of mzmine, I have resolved the problem by omitting the.mzML in the metadata and making the first column of header namely filename, not another. Many thanks

**Comment by robinschmid** [comment]
It seems like there was a space at the end of the filenames? 
![image](https://github.com/user-attachments/assets/52460ae0-dbea-41ad-bfcc-624104b33015)

**Comment by GenesiskaGenesiska** [comment]
Hi Robin, that problem was resolved successfully  as I mentioned by omitting the ".mzML" in my filename of metadata, as here appears 

<img width="1147" alt="Screenshot 2024-11-18 at 2 37 30 PM" src="https://github.com/user-attachments/assets/67f24123-2949-4f1c-a8ef-4cb49f27a493">

Meanwhile, another problem is not compatible to save them in PNG/jpg/pdf; they always appear zero bytes and the error notification is as here. What I did was right-click and export graphics>select the folder and make the filename, and save. 

<img width="1147" alt="Screenshot 2024-11-18 at 3 49 40 PM" src="https://github.com/user-attachments/assets/6a7547bd-ac1e-4f59-990f-e49bb7777457">

Do I miss the other things to setup?

**Comment by SteffenHeu** [comment]
Hi @GenesiskaGenesiska,

the export issue was caused by an internal conversion error which lead to the high width/height values. The issue has been resolved in 4.4.3. Simply lower the dimensions and it should work fine.
